spring.application.name=eshop
spring.datasource.url=jdbc:mysql://localhost:3306/newclothing_store

server.port=8080

spring.datasource.username=root
spring.datasource.password=SaThSaRa@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true